---
- name: Build images
  gather_facts: No
  hosts: localhost

  tasks:
  - name: Docker Login
    docker_login:
      registry: https://gcr.io
      username: _json_key
      debug: true
      password: " {{ lookup('file', '/var/lib/jenkins/credentials/project-for-terraform.json')}}"

  - name: Clone front-end
    git:
      repo: 'https://github.com/Ginungagap/front-end.git'
      dest: /var/lib/jenkins/repositories/front-end

  - name: Build and push front-end image
    docker_image:
      build:
        path: /var/lib/jenkins/repositories/front-end
      name: gcr.io/project-for-terraform/front-end
      tag: "3.0.0, latest"
      force_tag: yes
      push: yes
      source: build

  # - name: Remove front-end image
  #   docker_image:
  #     state: absent
  #     name: gcr.io/project-for-terraform/front-end
