---
- name: Install Docker
  gather_facts: yes
  hosts: docker
  become: yes 
 
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
 
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
 
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
 
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
       
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user jenkins to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Creates directory for carts container
      file:
        path: /app/carts
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0774     
        
    - name: Creates directory for docker swarm key
      file:
        path: /home/jenkins/docker_credentials/
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0774     
        